name: onur
description: easily manage multiple floss repositories.
version: 0.1.0
repository: https://gitlab.com/easbarba/onur-dart

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
